#!/usr/bin/env python3

from __future__ import annotations

import argparse
from decimal import Decimal, ROUND_HALF_UP, getcontext
from pathlib import Path

getcontext().prec = 100

PI = Decimal(
    "3.141592653589793238462643383279502884197169399375105820974944592307816406286"
    "2089986280348253421170679"
)
TWO_PI = PI * 2
Q31_SCALE = Decimal(1 << 31)


def cos_decimal(angle: Decimal) -> Decimal:
    reduced = angle % TWO_PI
    if reduced > PI:
        reduced -= TWO_PI

    squared = reduced * reduced
    term = Decimal(1)
    total = term
    index = 1
    threshold = Decimal(1).scaleb(-90)
    while True:
        term *= -squared / Decimal((2 * index - 1) * (2 * index))
        total += term
        if abs(term) < threshold:
            return total
        index += 1


def coefficients() -> list[int]:
    result: list[int] = []
    for index in range(512):
        angle = TWO_PI * Decimal(index) / Decimal(511)
        hann = (Decimal(1) - cos_decimal(angle)) / Decimal(2)
        result.append(int((hann * Q31_SCALE).to_integral_value(rounding=ROUND_HALF_UP)))
    return result


def fnv1a64(values: list[int]) -> int:
    checksum = 0x14650FB0739D0383
    for value in values:
        for byte in value.to_bytes(4, byteorder="little", signed=True):
            checksum ^= byte
            checksum = (checksum * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return checksum


def render(values: list[int]) -> str:
    lines = [
        "#ifndef LOCAL_ACR_FINGERPRINT_HANN_Q31_HPP",
        "#define LOCAL_ACR_FINGERPRINT_HANN_Q31_HPP",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace local_acr {",
        "",
        "// Generated by tools/generate_hann_q31.py from",
        "// 0.5 * (1 - cos(2*pi*n/511)), rounded to Q1.31 ties away from zero.",
        "inline constexpr std::array<std::int32_t, 512> kHannQ31{",
    ]
    for offset in range(0, len(values), 8):
        chunk = ", ".join(str(value) for value in values[offset : offset + 8])
        lines.append(f"    {chunk},")
    lines.extend(
        [
            "};",
            "",
            "}  // namespace local_acr",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    values = coefficients()
    if values != list(reversed(values)):
        raise RuntimeError("Hann coefficients are not symmetric")
    if values[0] != 0 or values[-1] != 0:
        raise RuntimeError("Hann endpoints are not zero")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(values), encoding="utf-8")
    print(f"center={values[255]} checksum=0x{fnv1a64(values):016X}")


if __name__ == "__main__":
    main()
