function(lacr_apply_sanitizers target)
  if(LACR_ENABLE_ASAN_UBSAN)
    target_compile_options("${target}" PRIVATE -fno-omit-frame-pointer -fsanitize=address,undefined)
    target_link_options("${target}" PRIVATE -fno-omit-frame-pointer -fsanitize=address,undefined)
  elseif(LACR_ENABLE_TSAN)
    target_compile_options("${target}" PRIVATE -fno-omit-frame-pointer -fsanitize=thread)
    target_link_options("${target}" PRIVATE -fno-omit-frame-pointer -fsanitize=thread)
  endif()
endfunction()
